server:
  servlet:
    context-path: /springback
  port: 8080

spring:
  h2:
    console:
      enabled: true 
      path: /h2
   
  datasource:
    url: jdbc:h2:file:~/h2db
    username: h2sa
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
     hibernate:
     
     
      